/*************************************************************************
    * Created by: anastasiyakovalchuk
    * Created date: 18 February 2020
    * Description: 
    * History:
************************************************************************/

public with sharing class Constants {

    public static final String STORY_LOG_TYPE_FIELD_UPDATE = 'FieldUpdate';
    public static final String STORY_LOG_TYPE_RELATED_OBJECT = 'RelatedObject';
    public static final String STORY_LOG_TYPE_RELATED_FILE = 'RelatedFile';
}