@IsTest
private with sharing class SuperControllerTest {/*

    @IsTest
    public static void testFakeController(){
        // when
        Response testResponse = SuperController.execute('INVALID_CONTROLLER', null);

        // then
        System.assertEquals(false, testResponse.isSuccess);
        System.assertEquals(null, testResponse.responseObj);
        
        testResponse = SuperController.execute('EngageAccNewBusinessIndicatorController', new Map<String, Object>{ 'actionName' => 'initData', 'recordId' => '' });
    }*/
}